---
title: "problem 2"
author: "Harry Woo"
date: '2020 6 16 '
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Package Loading
rm(list = ls())
library(tseries)
library(mFilter)
library(ggfortify)
library(forecast)
library(gridExtra)

# Data Loading
gdp  <- read.csv("gdpq.csv", header = TRUE)
gdp_sa <- ts(gdp[,1]/1000, start = 1982, frequency = 4)
```

```{r}
plot1 <- autoplot(gdp_sa, series = "계절조정") + xlab("Time") + ylab("GDP") + 
  theme(plot.title = element_text(size = 18, hjust = 0.5, vjust = 1.5, face = "bold"))
plot1 + ggtitle(label = "GDP 계절조정계열 (분기별, 실질)") +
  scale_colour_manual(values = "royalblue") + theme(legend.position = "none")
```

```{r}
# GDP 변동요인 분해 (계절요인은 원 자료에서 이미 조정됨)
# 추세변동요인 계열 추출 1 : 로그변환한 계절조정계열에 호드릭-프레스콧(HP) 필터를 적용
lgdp_sa <- log(gdp_sa)
lgdp_hp <- mFilter(lgdp_sa, filter = "HP", lambda = 1600)
```

```{r}
# 추세변동요인 계열 추출 2 : 지수함수를 이용하여 GDP 추세계열로 전환
gdp_trend <- exp(lgdp_hp$trend)
```

```{r}
# 계절조정계열 vs. 추세변동요인 계열
plot1 + autolayer(gdp_trend, series = "추세계열") +
  ggtitle("GDP 계절조정 vs GDP 추세계열") +
  scale_colour_manual(values = c("계절조정" = "royalblue", "추세계열" = "red")) +
  theme(legend.position = c(0.15, 0.8))

```

```{r}
lgdp_sam <- (lgdp_sa + lag(lgdp_sa, -1)+ lag(lgdp_sa, 1))/3 # 중심화이동평균
lgdp_cycle <- lgdp_sam - lgdp_hp$trend
gdp_cycle <- exp(lgdp_cycle) * 100 # 지수함수, 100-scale

```

```{r}
# 100을 기준으로 순환변동요인 계산 (100 이상 호황, 이하 불황)
# gdp_sam <- exp(lgdp_sam) #지수함수
# gdp_cycle2 <- gdp_sam / gdp_trend * 100
# gdp_irregular <- gdp_sa / gdp_sam * 100 # 졸려

# 순환변동요인을 로그차분을 고려해 계산하면 아래와 같음
# lgdp_trend <- lgdp_hp$trend #추세
# lgdp_cycle <- lgdp_sam - lgdp_trend
# exp(lgdp_cycle) * 100 == gdp_cycle
```

```{r}
# 순환변동요인 계열 그래프로 표현
autoplot(gdp_cycle, lwd = 1, col = "royalblue") +
  geom_hline(yintercept = 100, lty = 2, col = "black") +
  geom_vline(xintercept = 2017.75, lty = 2, col = "red") +
  ylab("GDP 순환변동요인") + ggtitle(label = "GDP 순환변동치") +
  theme(plot.title = element_text(size = 18, hjust = 0.5, vjust = 1.5, face = "bold"))

# 기존 기준일과 대비해보고, 최근의 순환변동에 대한 코멘트로 마무리하면 되지 않을까?
# 외환위기에 대한 코멘트
```